CREATE TABLE latest_cv_images (
	DeviceID UInt32,
	VendorImageID String,
	CameraVersion LowCardinality(String),
	VendorDeviceID LowCardinality(String),
	CaptureTimestampUTC DATETIME CODEC(Delta, ZSTD),
	ImageBucket LowCardinality(String),
	ImageFormat LowCardinality(String),
	ModifiedDateTimeUTC DateTime64 CODEC(Delta, ZSTD),
	CreatedDateTimeUTC DateTime64 CODEC(Delta, ZSTD),
	CaptureDateTimeUTC DateTime64 CODEC(Delta, ZSTD),
    ImageAssembledDateTimeUTC DateTime64 CODEC(Delta, ZSTD),
    CVAssessmentDateTimeUTC DateTime64 CODEC(Delta, ZSTD),
	IsComplete Boolean,
	AmbientLight Int32,
	Contrast UInt8,
	Brightness UInt8,
	Exposure UInt8,
	Resolution UInt8,
	ImageUrl String,
	TransmissionCaptureDateTimeUTC DateTime64 CODEC(Delta, ZSTD),
	ImageID UInt32 CODEC(Delta, ZSTD),
	NightClearPavement DECIMAL(4, 2),
	NightSnowing DECIMAL(4, 2),
	NightWetPavement DECIMAL(4, 2),
	NightSnowOnRoad DECIMAL(4, 2),
	NightPartialSnowOnRoad DECIMAL(4, 2),
	DaySnowing DECIMAL(4, 2),
	DayPartialSnowOnRoad DECIMAL(4, 2),
	DayClearPavement DECIMAL(4, 2),
	DayWetPavement DECIMAL(4, 2),
	DaySnowOnRoad DECIMAL(4, 2),
	Night DECIMAL(4, 2),
	Sunny DECIMAL(4, 2),
	Cloudy DECIMAL(4, 2),
	ClearPavement DECIMAL(4, 2),
	WetPavement DECIMAL(4, 2),
	SnowOnRoad DECIMAL(4, 2),
	PartialSnowOnRoad DECIMAL(4, 2),
	Snowing DECIMAL(4, 2),
	Raining DECIMAL(4, 2),
	ModelVersion LowCardinality(String),
	IcedLens DECIMAL(4, 2),
	Version Int8,
    IsBurstImage Boolean
) ENGINE = ReplacingMergeTree(CaptureDateTimeUTC)
ORDER BY (
		DeviceID
	)
PARTITION BY toStartOfMonth(CaptureDateTimeUTC)
