"""burst-url

Revision ID: b862baddcdcd
Revises: b259381d74f8
Create Date: 2025-04-17 16:00:43.352207

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "b862baddcdcd"
down_revision = "b259381d74f8"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "DeviceImages",
        sa.Column(
            "IsBurstImage",
            sa.Boolean(),
            server_default=sa.text("((0))"),
            nullable=False,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("DeviceImages", "IsBurstImage")
    # ### end Alembic commands ###
