"""remove-xtra-image-columns

Revision ID: b259381d74f8
Revises: 9c95654a68db
Create Date: 2025-02-25 11:25:56.463843

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "b259381d74f8"
down_revision = "9c95654a68db"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("IDX_ImageUrlProcessed", table_name="DeviceImages")
    op.drop_index("IDX_ImageUrlUpscale", table_name="DeviceImages")
    op.drop_column("DeviceImages", "ImageUrlProcessed")
    op.drop_column("DeviceImages", "ImageUrlUpscale")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "DeviceImages",
        sa.Column(
            "ImageUrlUpscale",
            sa.VARCHAR(length=5000, collation="SQL_Latin1_General_CP1_CI_AS"),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "DeviceImages",
        sa.Column(
            "ImageUrlProcessed",
            sa.VARCHAR(length=5000, collation="SQL_Latin1_General_CP1_CI_AS"),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.create_index(
        "IDX_ImageUrlUpscale", "DeviceImages", ["ImageUrlUpscale"], unique=False
    )
    op.create_index(
        "IDX_ImageUrlProcessed", "DeviceImages", ["ImageUrlProcessed"], unique=False
    )
    # ### end Alembic commands ###
