"""req-notif-mapping

Revision ID: 73584fb106fc
Revises: 8b8b024f50c9
Create Date: 2025-04-25 11:38:42.112333

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "73584fb106fc"
down_revision = "8b8b024f50c9"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "RequestTypeNotificationTypeMap",
        sa.Column(
            "ID",
            sa.BigInteger(),
            sa.Identity(always=False, start=1, increment=1),
            nullable=False,
        ),
        sa.Column(
            "RequestTypeCode",
            sa.String(length=30, collation="SQL_Latin1_General_CP1_CI_AS"),
            nullable=False,
        ),
        sa.Column(
            "NotificationTypeName",
            sa.String(length=30, collation="SQL_Latin1_General_CP1_CI_AS"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["NotificationTypeName"],
            ["NotificationType.Name"],
            name=op.f(
                "fk_RequestTypeNotificationTypeMap_NotificationTypeName_NotificationType"
            ),
        ),
        sa.ForeignKeyConstraint(
            ["RequestTypeCode"],
            ["RequestType.RequestTypeCode"],
            name=op.f("fk_RequestTypeNotificationTypeMap_RequestTypeCode_RequestType"),
        ),
        sa.PrimaryKeyConstraint("ID", name=op.f("pk_RequestTypeNotificationTypeMap")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("RequestTypeNotificationTypeMap")
    # ### end Alembic commands ###
