"""req-notif-mapping-seed

Revision ID: 32879064aa8f
Revises: 73584fb106fc
Create Date: 2025-04-25 11:39:13.095208

"""

import sqlalchemy as sa
from alembic import op

from schemas.schema import NotificationType, RequestTypeNotificationTypeMap
from seeds.req_notif_map import MAP, NEW_NOTIFICATION_TYPES

# revision identifiers, used by Alembic.
revision = "32879064aa8f"
down_revision = "73584fb106fc"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.bulk_insert(
        NotificationType.__table__,
        [
            {
                "Name": name,
                "Description": description,
                "ID": id,
            }
            for (name, description, id) in NEW_NOTIFICATION_TYPES
        ],
    )
    op.bulk_insert(
        RequestTypeNotificationTypeMap.__table__,
        [
            {
                "RequestTypeCode": request_type,
                "NotificationTypeName": notification_type,
            }
            for notification_type, request_type in MAP.items()
        ],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        RequestTypeNotificationTypeMap.__table__.delete().where(
            RequestTypeNotificationTypeMap.RequestTypeCode.in_(MAP.values())
        )
    )
    # ### end Alembic commands ###
