"""create_alert_triggers_notifications

Revision ID: 70f1e4be0d45
Revises: 2db78109f177
Create Date: 2025-05-30 17:51:24.262060

"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mssql

# revision identifiers, used by Alembic.
revision = "70f1e4be0d45"
down_revision = "2db78109f177"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "AlertTriggers",
        sa.Column(
            "ID",
            sa.BigInteger(),
            sa.Identity(always=False, start=1, increment=1),
            nullable=False,
        ),
        sa.Column("AlertID", mssql.UNIQUEIDENTIFIER(), nullable=False),
        sa.Column("DeviceID", sa.BigInteger(), nullable=False),
        sa.Column("DateTimeUTC", mssql.DATETIME2(), nullable=False),
        sa.ForeignKeyConstraint(
            ["AlertID"], ["Alerts.ID"], name=op.f("fk_AlertTriggers_AlertID_Alerts")
        ),
        sa.ForeignKeyConstraint(
            ["DeviceID"], ["Devices.ID"], name=op.f("fk_AlertTriggers_DeviceID_Devices")
        ),
        sa.PrimaryKeyConstraint("ID", name=op.f("pk_AlertTriggers")),
    )
    op.create_index(
        "iDX_AlertTriggers_DeviceID_Includes_AlertID_DateTimeUTC",
        "AlertTriggers",
        ["DeviceID"],
        unique=False,
        mssql_include=["AlertID", "DateTimeUTC"],
    )
    op.create_table(
        "AlertNotifications",
        sa.Column(
            "ID",
            sa.BigInteger(),
            sa.Identity(always=False, start=1, increment=1),
            nullable=False,
        ),
        sa.Column("AlertTriggerID", sa.BigInteger(), nullable=False),
        sa.Column("UserID", mssql.UNIQUEIDENTIFIER(), nullable=False),
        sa.Column("DidSucceed", sa.Boolean(), nullable=False),
        sa.Column("DateTimeUTC", mssql.DATETIME2(), nullable=False),
        sa.Column("AlertBody", sa.Unicode(), nullable=True),
        sa.Column("OtherInformation", sa.Unicode(), nullable=True),
        sa.ForeignKeyConstraint(
            ["AlertTriggerID"],
            ["AlertTriggers.ID"],
            name=op.f("fk_AlertNotifications_AlertTriggerID_AlertTriggers"),
        ),
        sa.ForeignKeyConstraint(
            ["UserID"], ["Users.ID"], name=op.f("fk_AlertNotifications_UserID_Users")
        ),
        sa.PrimaryKeyConstraint("ID", name=op.f("pk_AlertNotifications")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("AlertNotifications")
    op.drop_index(
        "iDX_AlertTriggers_DeviceID_Includes_AlertID_DateTimeUTC",
        table_name="AlertTriggers",
        mssql_include=["AlertID", "DateTimeUTC"],
    )
    op.drop_table("AlertTriggers")
    # ### end Alembic commands ###
