"""generalize_encryption_keys

Revision ID: 7c073467cb11
Revises: ca6f216a0e74
Create Date: 2025-02-13 08:45:49.260042

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "7c073467cb11"
down_revision = "ca6f216a0e74"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table("SDSEncryptionKeys", "BluetoothEncryptionKeys")
    op.execute("CREATE SYNONYM SDSEncryptionKeys FOR BluetoothEncryptionKeys")
    # ### end Alembic commands ###


def downgrade() -> None:
    op.execute("DROP SYNONYM IF EXISTS SDSEncryptionKeys")
    op.rename_table("BluetoothEncryptionKeys", "SDSEncryptionKeys")
    # ### end Alembic commands ###
