"""add-sensor-height

Revision ID: cd9a9fab7cf6
Revises: 848f1e8db4a8
Create Date: 2024-10-31 14:40:34.096600

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "cd9a9fab7cf6"
down_revision = "848f1e8db4a8"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "Devices",
        sa.Column("SensorHeight", sa.DECIMAL(precision=10, scale=2), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("Devices", "SensorHeight")
    # ### end Alembic commands ###
