"""additional_fields_for_device_request_images

Revision ID: d10a9b293686
Revises: b3c039a75436
Create Date: 2025-07-02 11:29:57.945672

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "d10a9b293686"
down_revision = "b3c039a75436"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "DeviceRequestImages",
        sa.Column(
            "DeviceID",
            sa.BigInteger(),
            nullable=True,
        ),
    )
    op.add_column(
        "DeviceRequestImages",
        sa.Column(
            "CaptureDateTimeUTC",
            sa.DateTime(),
            nullable=True,
        ),
    )
    op.execute(
        """
        UPDATE DeviceRequestImages 
        SET DeviceID = CASE 
            WHEN DeviceImages.DeviceID IS NULL THEN 1
            ELSE DeviceImages.DeviceID
        END
        FROM DeviceRequestImages
        LEFT OUTER JOIN DeviceImages ON DeviceRequestImages.DeviceImageID = DeviceImages.ID 
        """
    )
    op.execute(
        """
        UPDATE DeviceRequestImages
        SET CaptureDateTimeUTC = CASE
            WHEN DeviceImages.CaptureDateTimeUTC IS NULL THEN '1900-01-01 00:00:00'
            ELSE DeviceImages.CaptureDateTimeUTC
        END 
        FROM DeviceRequestImages
        LEFT OUTER JOIN DeviceImages ON DeviceRequestImages.DeviceImageID = DeviceImages.ID
        """
    )
    op.create_foreign_key(
        op.f("fk_DeviceRequestImages_DeviceID_Devices"),
        "DeviceRequestImages",
        "Devices",
        ["DeviceID"],
        ["ID"],
    )
    op.alter_column(
        "DeviceRequestImages",
        "DeviceID",
        existing_type=sa.BigInteger(),
        nullable=False,
    )
    op.alter_column(
        "DeviceRequestImages",
        "CaptureDateTimeUTC",
        existing_type=sa.DateTime(),
        nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("fk_DeviceRequestImages_DeviceID_Devices"),
        "DeviceRequestImages",
        type_="foreignkey",
    )
    op.drop_column("DeviceRequestImages", "CaptureDateTimeUTC")
    op.drop_column("DeviceRequestImages", "DeviceID")
    # ### end Alembic commands ###
