"""remove_device_request_image_logic_from_stored_proc

Revision ID: 155ff6de6313
Revises: d10a9b293686
Create Date: 2025-07-02 11:40:28.232264

"""

from alembic import op
import sqlalchemy as sa
from schemas.stored_procedures import (
    usp_api_UpsertCompletedImage,
    usp_api_UpsertCompletedImage_rollback,
)

# revision identifiers, used by Alembic.
revision = "155ff6de6313"
down_revision = "d10a9b293686"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    usp_api_UpsertCompletedImage_rollback.drop_function(op)
    usp_api_UpsertCompletedImage.create_function(op)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    usp_api_UpsertCompletedImage.drop_function(op)
    usp_api_UpsertCompletedImage_rollback.create_function(op)
    # ### end Alembic commands ###
