"""trigger_data_column

Revision ID: 5e9de4f702c9
Revises: a29dca7286cb
Create Date: 2025-08-01 10:40:36.043995

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "5e9de4f702c9"
down_revision = "a29dca7286cb"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "AlertTriggers",
        sa.Column("TriggerData", sa.JSON(none_as_null=True), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("AlertTriggers", "TriggerData")
    # ### end Alembic commands ###
