"""device-types

Revision ID: 982473eca695
Revises: 649f90414e85
Create Date: 2024-07-02 11:58:04.467133

"""

from alembic import op
import sqlalchemy as sa
from schemas.helpers import set_default_device_type, insert_device_types
from schemas.schema import DeviceType

# revision identifiers, used by Alembic.
revision = "982473eca695"
down_revision = "649f90414e85"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "DeviceType",
        sa.Column(
            "ID",
            sa.SmallInteger(),
            sa.Identity(always=False, start=1, increment=1),
            nullable=False,
        ),
        sa.Column(
            "Name",
            sa.String(length=50, collation="SQL_Latin1_General_CP1_CI_AS"),
            nullable=False,
        ),
        sa.Column(
            "IsActive", sa.Boolean(), server_default=sa.text("((1))"), nullable=False
        ),
        sa.PrimaryKeyConstraint("ID", name=op.f("pk_DeviceType")),
    )
    insert_device_types(op, sa.orm)
    session = sa.orm.Session(bind=op.get_bind())
    device_type = (
        session.query(DeviceType).filter(DeviceType.Name == "Mini RWIS").first()
    )

    op.add_column(
        "Devices",
        sa.Column(
            "DeviceType",
            sa.SmallInteger(),
            server_default=sa.text(f"({device_type.ID})"),
            nullable=True,
        ),
    )

    set_default_device_type(op, sa.orm)
    op.alter_column(
        "Devices",
        "DeviceType",
        existing_type=sa.SmallInteger(),
        nullable=False,
    )
    op.create_index(
        op.f("Devices_DeviceType_IX"), "Devices", ["DeviceType"], unique=False
    )
    op.create_foreign_key(
        op.f("fk_Devices_DeviceType_DeviceType"),
        "Devices",
        "DeviceType",
        ["DeviceType"],
        ["ID"],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("fk_Devices_DeviceType_DeviceType"), "Devices", type_="foreignkey"
    )
    op.drop_index(op.f("Devices_DeviceType_IX"), table_name="Devices")
    op.drop_column("Devices", "DeviceType")
    op.drop_table("DeviceType")
    # ### end Alembic commands ###
