"""remove-reports

Revision ID: 62348926482b
Revises: 982473eca695
Create Date: 2024-07-05 09:45:21.002563

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mssql

# revision identifiers, used by Alembic.
revision = "62348926482b"
down_revision = "982473eca695"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("Reports")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "Reports",
        sa.Column(
            "ID",
            mssql.UNIQUEIDENTIFIER(),
            server_default=sa.text("(newid())"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "GroupID", mssql.UNIQUEIDENTIFIER(), autoincrement=False, nullable=False
        ),
        sa.Column("ReportType", sa.SMALLINT(), autoincrement=False, nullable=False),
        sa.Column(
            "ReportFrequency", sa.SMALLINT(), autoincrement=False, nullable=False
        ),
        sa.Column("IsDisabled", mssql.BIT(), autoincrement=False, nullable=False),
        sa.Column("IsActive", mssql.BIT(), autoincrement=False, nullable=False),
        sa.Column(
            "CreatedDateTimeUTC", mssql.DATETIME2(), autoincrement=False, nullable=False
        ),
        sa.Column(
            "CreatedUserID",
            mssql.UNIQUEIDENTIFIER(),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "ModifiedDateTimeUTC", mssql.DATETIME2(), autoincrement=False, nullable=True
        ),
        sa.Column(
            "ModifiedUserID",
            mssql.UNIQUEIDENTIFIER(),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column("DayOfWeek", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("DayOfMonth", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.ForeignKeyConstraint(
            ["CreatedUserID"], ["Users.ID"], name="Reports_CreatedUserID_FK"
        ),
        sa.ForeignKeyConstraint(["GroupID"], ["Groups.ID"], name="Reports_GroupID_FK"),
        sa.ForeignKeyConstraint(
            ["ModifiedUserID"], ["Users.ID"], name="Reports_ModifiedUserID_FK"
        ),
        sa.PrimaryKeyConstraint("ID", name="Reports_PK"),
    )
    # ### end Alembic commands ###
