"""track_upload

Revision ID: e1545a7a0c7b
Revises: 9ee1798eb5ff
Create Date: 2024-07-17 17:12:18.701623

"""

import sqlalchemy as sa
from alembic import op

from schemas.other_objects.functions import (
    usp_InsertSnowDepthReading,
    usp_InsertSnowDepthReadingV2,
)

# revision identifiers, used by Alembic.
revision = "e1545a7a0c7b"
down_revision = "9ee1798eb5ff"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "SnowDepthReadings", sa.Column("UploadedByRWIS", sa.BigInteger(), nullable=True)
    )
    op.create_foreign_key(
        op.f("fk_SnowDepthReadings_UploadedByRWIS_Devices"),
        "SnowDepthReadings",
        "Devices",
        ["UploadedByRWIS"],
        ["ID"],
    )
    usp_InsertSnowDepthReading.drop_function(op)
    usp_InsertSnowDepthReadingV2.create_function(op)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    usp_InsertSnowDepthReadingV2.drop_function(op)
    op.drop_constraint(
        op.f("fk_SnowDepthReadings_UploadedByRWIS_Devices"),
        "SnowDepthReadings",
        type_="foreignkey",
    )
    op.drop_column("SnowDepthReadings", "UploadedByRWIS")
    usp_InsertSnowDepthReading.create_function(op)
    # ### end Alembic commands ###
