"""hardware_revisions

Revision ID: a3c7f389aa3e
Revises: 62348926482b
Create Date: 2024-07-11 12:22:31.623503

"""

import sqlalchemy as sa
from alembic import op

from schemas.helpers import insert_revisions

# revision identifiers, used by Alembic.
revision = "a3c7f389aa3e"
down_revision = "62348926482b"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "BluetoothHardware",
        sa.Column(
            "ID",
            sa.BigInteger(),
            sa.Identity(always=False, start=1, increment=1),
            nullable=False,
        ),
        sa.Column(
            "ProductID",
            sa.String(length=8, collation="SQL_Latin1_General_CP1_CI_AS"),
            nullable=False,
            server_default=sa.text("('1')"),
        ),
        sa.Column(
            "SecretKey",
            sa.String(length=32, collation="SQL_Latin1_General_CP1_CI_AS"),
            nullable=False,
        ),
        sa.Column(
            "Name",
            sa.String(length=50, collation="SQL_Latin1_General_CP1_CI_AS"),
            nullable=True,
        ),
        sa.Column(
            "IsActive", sa.Boolean(), server_default=sa.text("((0))"), nullable=False
        ),
        sa.Column(
            "Description",
            sa.String(length=2000, collation="SQL_Latin1_General_CP1_CI_AS"),
            nullable=True,
        ),
        sa.PrimaryKeyConstraint("ID", name=op.f("pk_BluetoothHardware")),
    )
    op.create_table(
        "HardwareRevisions",
        sa.Column(
            "ID",
            sa.SmallInteger(),
            sa.Identity(always=False, start=1, increment=1),
            nullable=False,
        ),
        sa.Column(
            "Name",
            sa.String(length=50, collation="SQL_Latin1_General_CP1_CI_AS"),
            nullable=False,
        ),
        sa.Column(
            "IsActive", sa.Boolean(), server_default=sa.text("((0))"), nullable=False
        ),
        sa.Column(
            "Description",
            sa.String(length=2000, collation="SQL_Latin1_General_CP1_CI_AS"),
            nullable=True,
        ),
        sa.PrimaryKeyConstraint("ID", name=op.f("pk_HardwareRevisions")),
    )
    op.create_table(
        "DeviceRevisions",
        sa.Column("DeviceID", sa.BigInteger(), nullable=False),
        sa.Column("HardwareRevisionID", sa.SmallInteger(), nullable=False),
        sa.Column(
            "BluetoothRevisionID",
            sa.BigInteger(),
            nullable=True,
        ),
        sa.Column(
            "ModifiedDateTimeUTC",
            sa.DateTime(),
            server_default=sa.text("(getdate())"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["BluetoothRevisionID"],
            ["BluetoothHardware.ID"],
            name=op.f("fk_DeviceRevisions_BluetoothHardwareRevision_BluetoothHardware"),
        ),
        sa.ForeignKeyConstraint(
            ["DeviceID"],
            ["Devices.ID"],
            name=op.f("fk_DeviceRevisions_DeviceID_Devices"),
        ),
        sa.ForeignKeyConstraint(
            ["HardwareRevisionID"],
            ["HardwareRevisions.ID"],
            name=op.f("fk_DeviceRevisions_HardwareRevision_HardwareRevisions"),
        ),
        sa.PrimaryKeyConstraint("DeviceID", name=op.f("pk_DeviceRevisions")),
    )
    insert_revisions(op, sa.orm)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("DeviceRevisions")
    op.drop_table("HardwareRevisions")
    op.drop_table("BluetoothHardware")
    # ### end Alembic commands ###
