"""normalize_revisions2

Revision ID: 764bdfc890ae
Revises: 5a4388cf309d
Create Date: 2024-08-30 13:46:53.513061

"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mssql

# revision identifiers, used by Alembic.
revision = "764bdfc890ae"
down_revision = "5a4388cf309d"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("DeviceRevisions")
    op.drop_table("HardwareRevisions")
    op.add_column(
        "FrostDeviceRevisions",
        sa.Column("SensorHardwareID", sa.SmallInteger(), nullable=True),
    )
    op.add_column(
        "FrostDeviceRevisions",
        sa.Column("BluetoothHardwareID", sa.BigInteger(), nullable=True),
    )
    op.drop_constraint(
        "fk_FrostDeviceRevisions_HardwareRevisionID_SensorHardware",
        "FrostDeviceRevisions",
        type_="foreignkey",
    )
    op.drop_constraint(
        "fk_FrostDeviceRevisions_BluetoothRevisionID_BluetoothHardware",
        "FrostDeviceRevisions",
        type_="foreignkey",
    )
    op.create_foreign_key(
        op.f("fk_FrostDeviceRevisions_SensorHardwareID_SensorHardware"),
        "FrostDeviceRevisions",
        "SensorHardware",
        ["SensorHardwareID"],
        ["ID"],
    )
    op.create_foreign_key(
        op.f("fk_FrostDeviceRevisions_BluetoothHardwareID_BluetoothHardware"),
        "FrostDeviceRevisions",
        "BluetoothHardware",
        ["BluetoothHardwareID"],
        ["ID"],
    )
    op.drop_column("FrostDeviceRevisions", "HardwareRevisionID")
    op.drop_column("FrostDeviceRevisions", "BluetoothRevisionID")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "FrostDeviceRevisions",
        sa.Column(
            "BluetoothRevisionID", sa.BIGINT(), autoincrement=False, nullable=True
        ),
    )
    op.add_column(
        "FrostDeviceRevisions",
        sa.Column(
            "HardwareRevisionID", sa.SMALLINT(), autoincrement=False, nullable=True
        ),
    )
    op.drop_constraint(
        op.f("fk_FrostDeviceRevisions_BluetoothHardwareID_BluetoothHardware"),
        "FrostDeviceRevisions",
        type_="foreignkey",
    )
    op.drop_constraint(
        op.f("fk_FrostDeviceRevisions_SensorHardwareID_SensorHardware"),
        "FrostDeviceRevisions",
        type_="foreignkey",
    )
    op.create_foreign_key(
        "fk_FrostDeviceRevisions_BluetoothRevisionID_BluetoothHardware",
        "FrostDeviceRevisions",
        "BluetoothHardware",
        ["BluetoothRevisionID"],
        ["ID"],
    )
    op.create_foreign_key(
        "fk_FrostDeviceRevisions_HardwareRevisionID_SensorHardware",
        "FrostDeviceRevisions",
        "SensorHardware",
        ["HardwareRevisionID"],
        ["ID"],
    )
    op.drop_column("FrostDeviceRevisions", "BluetoothHardwareID")
    op.drop_column("FrostDeviceRevisions", "SensorHardwareID")
    op.create_table(
        "HardwareRevisions",
        sa.Column(
            "ID",
            sa.SMALLINT(),
            sa.Identity(always=False, start=1, increment=1),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column(
            "Name",
            sa.VARCHAR(length=50, collation="SQL_Latin1_General_CP1_CI_AS"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "IsActive",
            mssql.BIT(),
            server_default=sa.text("((0))"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "Description",
            sa.VARCHAR(length=2000, collation="SQL_Latin1_General_CP1_CI_AS"),
            autoincrement=False,
            nullable=True,
        ),
        sa.PrimaryKeyConstraint("ID", name="pk_HardwareRevisions"),
    )
    op.create_table(
        "DeviceRevisions",
        sa.Column("DeviceID", sa.BIGINT(), autoincrement=False, nullable=False),
        sa.Column(
            "HardwareRevisionID", sa.SMALLINT(), autoincrement=False, nullable=False
        ),
        sa.Column(
            "BluetoothRevisionID", sa.BIGINT(), autoincrement=False, nullable=True
        ),
        sa.Column(
            "ModifiedDateTimeUTC",
            sa.DATETIME(),
            server_default=sa.text("(getdate())"),
            autoincrement=False,
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["BluetoothRevisionID"],
            ["BluetoothHardware.ID"],
            name="fk_DeviceRevisions_BluetoothHardwareRevision_BluetoothHardware",
        ),
        sa.ForeignKeyConstraint(
            ["DeviceID"], ["Devices.ID"], name="fk_DeviceRevisions_DeviceID_Devices"
        ),
        sa.ForeignKeyConstraint(
            ["HardwareRevisionID"],
            ["HardwareRevisions.ID"],
            name="fk_DeviceRevisions_HardwareRevision_HardwareRevisions",
        ),
        sa.PrimaryKeyConstraint("DeviceID", name="pk_DeviceRevisions"),
    )
    # ### end Alembic commands ###
