"""match_snow_depth

Revision ID: 471ea2c58b7d
Revises: 753144b95918
Create Date: 2024-07-25 13:12:17.381917

"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mssql

# revision identifiers, used by Alembic.
revision = "471ea2c58b7d"
down_revision = "753144b95918"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "SnowDepthRWISPairs",
        sa.Column(
            "ID",
            sa.BigInteger(),
            sa.Identity(always=False, start=1, increment=1),
            nullable=False,
        ),
        sa.Column("RWISDeviceID", sa.BigInteger(), nullable=False),
        sa.Column("SnowDepthDeviceID", sa.BigInteger(), nullable=False),
        sa.Column(
            "CreatedDateTimeUTC",
            sa.DateTime(),
            server_default=sa.text("(getdate())"),
            nullable=False,
        ),
        sa.Column(
            "ModifiedDateTimeUTC",
            sa.DateTime(),
            server_default=sa.text("(getdate())"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["RWISDeviceID"],
            ["Devices.ID"],
            name=op.f("fk_SnowDepthRWISPairs_RWISDeviceID_Devices"),
        ),
        sa.ForeignKeyConstraint(
            ["SnowDepthDeviceID"],
            ["Devices.ID"],
            name=op.f("fk_SnowDepthRWISPairs_SnowDepthDeviceID_Devices"),
        ),
        sa.PrimaryKeyConstraint("ID", name=op.f("pk_SnowDepthRWISPairs")),
        sa.UniqueConstraint("ID", name=op.f("uq_SnowDepthRWISPairs_ID")),
    )
    op.create_index(
        "IDX_SnowDepthRWISPairs_RWISDeviceID_SnowDepthDeviceID",
        "SnowDepthRWISPairs",
        ["RWISDeviceID", "SnowDepthDeviceID"],
        unique=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "IDX_SnowDepthRWISPairs_RWISDeviceID_SnowDepthDeviceID",
        table_name="SnowDepthRWISPairs",
    )
    op.drop_table("SnowDepthRWISPairs")
    # ### end Alembic commands ###
