"""nullable-sds-data

Revision ID: 848f1e8db4a8
Revises: 3a6e654c21a9
Create Date: 2024-10-30 17:14:17.059862

"""

import sqlalchemy as sa
from alembic import op

from schemas.other_objects.functions import (
    usp_InsertSnowDepthReadingV2,
    usp_InsertSnowDepthReadingV3,
)

# revision identifiers, used by Alembic.
revision = "848f1e8db4a8"
down_revision = "3a6e654c21a9"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "SnowDepthReadings", "BatteryMv", existing_type=sa.INTEGER(), nullable=True
    )
    op.alter_column(
        "SnowDepthReadings", "RssiPower", existing_type=sa.SMALLINT(), nullable=True
    )
    op.alter_column(
        "SnowDepthReadings", "Version", existing_type=sa.INTEGER(), nullable=True
    )
    op.alter_column(
        "SnowDepthReadings", "TemperatureC", existing_type=sa.SMALLINT(), nullable=True
    )
    op.alter_column(
        "SnowDepthReadings", "Reserved1", existing_type=sa.SMALLINT(), nullable=True
    )
    op.alter_column(
        "SnowDepthReadings", "Reserved2", existing_type=sa.SMALLINT(), nullable=True
    )
    # ### end Alembic commands ###
    usp_InsertSnowDepthReadingV2.drop_function(op)
    usp_InsertSnowDepthReadingV3.create_function(op)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "SnowDepthReadings", "Reserved2", existing_type=sa.SMALLINT(), nullable=False
    )
    op.alter_column(
        "SnowDepthReadings", "Reserved1", existing_type=sa.SMALLINT(), nullable=False
    )
    op.alter_column(
        "SnowDepthReadings", "TemperatureC", existing_type=sa.SMALLINT(), nullable=False
    )
    op.alter_column(
        "SnowDepthReadings", "Version", existing_type=sa.INTEGER(), nullable=False
    )
    op.alter_column(
        "SnowDepthReadings", "RssiPower", existing_type=sa.SMALLINT(), nullable=False
    )
    op.alter_column(
        "SnowDepthReadings", "BatteryMv", existing_type=sa.INTEGER(), nullable=False
    )
    # ### end Alembic commands ###
    usp_InsertSnowDepthReadingV3.drop_function(op)
    usp_InsertSnowDepthReadingV2.create_function(op)
