"""alerts_cond1_nullables

Revision ID: a9799105213f
Revises: ab3ae58d8250
Create Date: 2025-01-03 16:32:29.590239

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "a9799105213f"
down_revision = "ab3ae58d8250"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("Alerts", "Threshold1", existing_type=sa.SMALLINT(), nullable=True)
    op.alter_column("Alerts", "Temperature1", existing_type=sa.INTEGER(), nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "Alerts", "Temperature1", existing_type=sa.INTEGER(), nullable=False
    )
    op.alter_column("Alerts", "Threshold1", existing_type=sa.SMALLINT(), nullable=False)
    # ### end Alembic commands ###
