"""
Adds the DeviceLineage table to track changes to DeviceState

Revision ID: 086ffb27dd84
Revises: 72aa2fb15cf8
Create Date: 2023-09-05 11:45:58.726604

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mssql

# revision identifiers, used by Alembic.
revision = "086ffb27dd84"
down_revision = "72aa2fb15cf8"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "DeviceLineage",
        sa.Column(
            "ID",
            sa.BigInteger(),
            sa.Identity(always=False, start=0, increment=1),
            nullable=False,
        ),
        sa.Column("GroupID", sa.BigInteger(), nullable=False),
        sa.Column("DeviceId", sa.BigInteger(), nullable=False),
        sa.Column("OldDeviceState", sa.SmallInteger(), nullable=True),
        sa.Column("NewDeviceState", sa.SmallInteger(), nullable=False),
        sa.Column(
            "VendorDeviceID",
            sa.String(length=50, collation="SQL_Latin1_General_CP1_CI_AS"),
            nullable=False,
        ),
        sa.Column("CreatedDateTimeUTC", mssql.DATETIME2(), nullable=True),
        sa.ForeignKeyConstraint(
            ["DeviceId"], ["Devices.ID"], name=op.f("fk_DeviceLineage_DeviceId_Devices")
        ),
        sa.ForeignKeyConstraint(
            ["GroupID"],
            ["Groups.GroupID"],
            name=op.f("fk_DeviceLineage_GroupID_Groups"),
        ),
        sa.ForeignKeyConstraint(
            ["NewDeviceState"],
            ["DeviceStateType.ID"],
            name=op.f("fk_DeviceLineage_NewDeviceState_DeviceStateType"),
        ),
        sa.ForeignKeyConstraint(
            ["OldDeviceState"],
            ["DeviceStateType.ID"],
            name=op.f("fk_DeviceLineage_OldDeviceState_DeviceStateType"),
        ),
        sa.PrimaryKeyConstraint(
            "ID", name=op.f("pk_DeviceLineage"), mssql_clustered=False
        ),
    )
    op.create_index(
        op.f("DeviceLineage_VendorDeviceID_IX"),
        "DeviceLineage",
        ["VendorDeviceID"],
        unique=False,
    )
    op.create_index(
        "IDX_CreatedDateTimeUTC",
        "DeviceLineage",
        [sa.text("[CreatedDateTimeUTC] DESC")],
        unique=False,
        mssql_clustered=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "IDX_CreatedDateTimeUTC", table_name="DeviceLineage", mssql_clustered=True
    )
    op.drop_index(op.f("DeviceLineage_VendorDeviceID_IX"), table_name="DeviceLineage")
    op.drop_table("DeviceLineage")
    # ### end Alembic commands ###
