"""new_alert_logs_table

Revision ID: 094379e75d4c
Revises: f6a6f779f5dd
Create Date: 2024-02-20 11:20:55.442759

"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mssql

# revision identifiers, used by Alembic.
revision = "094379e75d4c"
down_revision = "f6a6f779f5dd"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "AlertLogsNew",
        sa.Column(
            "ID",
            mssql.UNIQUEIDENTIFIER(),
            server_default=sa.text("(newid())"),
            nullable=False,
        ),
        sa.Column("AlertID", mssql.UNIQUEIDENTIFIER(), nullable=False),
        sa.Column("UserID", mssql.UNIQUEIDENTIFIER(), nullable=False),
        sa.Column("SentDateTimeUTC", mssql.DATETIME2(), nullable=False),
        sa.Column("DeliveryMethod", sa.SmallInteger(), nullable=False),
        sa.Column("Contact", sa.Unicode(length=100), nullable=False),
        sa.Column("DeviceID", sa.BigInteger(), nullable=False),
        sa.Column("DeliverySucceeded", sa.Boolean(), nullable=False),
        sa.Column("AlertBody", sa.Unicode(), nullable=False),
        sa.Column("LatestTransmissionDateTimeUTC", mssql.DATETIME2(), nullable=True),
        sa.Column("NextForecastDateTimeUTC", mssql.DATETIME2(), nullable=True),
        sa.ForeignKeyConstraint(
            ["AlertID"], ["Alerts.ID"], name=op.f("fk_AlertLogsNew_AlertID_Alerts")
        ),
        sa.ForeignKeyConstraint(
            ["DeviceID"], ["Devices.ID"], name=op.f("fk_AlertLogsNew_DeviceID_Devices")
        ),
        sa.ForeignKeyConstraint(
            ["UserID"], ["Users.ID"], name=op.f("fk_AlertLogsNew_UserID_Users")
        ),
        sa.PrimaryKeyConstraint("ID", name=op.f("pk_AlertLogsNew")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("AlertLogsNew")
    # ### end Alembic commands ###
