"""groupid-change-datalineage

Revision ID: 9c4abca82eb3
Revises: 11f626774316
Create Date: 2023-10-27 13:00:50.006853

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "9c4abca82eb3"
down_revision = "11f626774316"
branch_labels = None
depends_on = None


TABLE_NAME = "DeviceLineage"

from schemas.other_objects.triggers import (
    ADD_GROUP_CHANGE_TO_DEVICE_LINEAGE,
    DEVICE_STATE_CHANGE,
)
from schemas.other_objects.groupid_change_datalineage import (
    build_prev_id_map,
    get_lineage_old_schema,
    set_default_device_lineage_columns,
    set_old_columns,
)


def upgrade() -> None:
    results = get_lineage_old_schema(sa, op)
    change_log = build_prev_id_map(results)
    # ### commands auto generated by Alembic - please adjust! ###
    DEVICE_STATE_CHANGE.drop_trigger(op)
    op.add_column(TABLE_NAME, sa.Column("NewGroupID", sa.BigInteger(), nullable=True))
    op.add_column(TABLE_NAME, sa.Column("OldGroupID", sa.BigInteger(), nullable=True))
    op.add_column(
        TABLE_NAME,
        sa.Column(
            "OldVendorDeviceID",
            sa.String(length=50, collation="SQL_Latin1_General_CP1_CI_AS"),
            nullable=True,
        ),
    )
    op.add_column(
        TABLE_NAME,
        sa.Column(
            "NewVendorDeviceID",
            sa.String(length=50, collation="SQL_Latin1_General_CP1_CI_AS"),
            nullable=True,
        ),
    )
    set_default_device_lineage_columns(op, sa.orm, change_log)
    op.alter_column(
        "DeviceLineage", "NewGroupID", existing_type=sa.BigInteger(), nullable=False
    )
    op.alter_column(
        "DeviceLineage", "OldGroupID", existing_type=sa.BigInteger(), nullable=False
    )
    op.alter_column(
        "DeviceLineage",
        "NewVendorDeviceID",
        existing_type=sa.String(50),
        nullable=False,
    )
    op.alter_column(
        "DeviceLineage",
        "OldVendorDeviceID",
        existing_type=sa.String(50),
        nullable=False,
    )
    op.drop_index("DeviceLineage_VendorDeviceID_IX", table_name=TABLE_NAME)
    op.create_index(
        op.f("DeviceLineage_NewVendorDeviceID_IX"),
        TABLE_NAME,
        ["NewVendorDeviceID"],
        unique=False,
    )
    op.create_index(
        op.f("DeviceLineage_OldVendorDeviceID_IX"),
        TABLE_NAME,
        ["OldVendorDeviceID"],
        unique=False,
    )
    op.drop_constraint(
        "fk_DeviceLineage_GroupID_Groups", TABLE_NAME, type_="foreignkey"
    )
    op.create_foreign_key(
        op.f("fk_DeviceLineage_OldGroupID_Groups"),
        TABLE_NAME,
        "Groups",
        ["OldGroupID"],
        ["GroupID"],
    )
    op.create_foreign_key(
        op.f("fk_DeviceLineage_NewGroupID_Groups"),
        TABLE_NAME,
        "Groups",
        ["NewGroupID"],
        ["GroupID"],
    )
    op.drop_column(TABLE_NAME, "VendorDeviceID")
    op.drop_column(TABLE_NAME, "GroupID")
    ADD_GROUP_CHANGE_TO_DEVICE_LINEAGE.create_trigger(op)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    ADD_GROUP_CHANGE_TO_DEVICE_LINEAGE.drop_trigger(op)
    op.add_column(
        TABLE_NAME,
        sa.Column("GroupID", sa.BIGINT(), autoincrement=False, nullable=True),
    )
    op.add_column(
        TABLE_NAME,
        sa.Column(
            "VendorDeviceID",
            sa.VARCHAR(length=50, collation="SQL_Latin1_General_CP1_CI_AS"),
            autoincrement=False,
            nullable=True,
        ),
    )
    set_old_columns(op, sa.orm)
    op.alter_column(
        "DeviceLineage", "GroupID", existing_type=sa.BigInteger(), nullable=False
    )
    op.alter_column(
        "DeviceLineage",
        "VendorDeviceID",
        existing_type=sa.String(50),
        nullable=False,
    )
    op.drop_constraint(
        op.f("fk_DeviceLineage_NewGroupID_Groups"), TABLE_NAME, type_="foreignkey"
    )
    op.drop_constraint(
        op.f("fk_DeviceLineage_OldGroupID_Groups"), TABLE_NAME, type_="foreignkey"
    )
    op.create_foreign_key(
        "fk_DeviceLineage_GroupID_Groups",
        TABLE_NAME,
        "Groups",
        ["GroupID"],
        ["GroupID"],
    )
    op.drop_index(op.f("DeviceLineage_OldVendorDeviceID_IX"), table_name=TABLE_NAME)
    op.drop_index(op.f("DeviceLineage_NewVendorDeviceID_IX"), table_name=TABLE_NAME)
    op.create_index(
        "DeviceLineage_VendorDeviceID_IX",
        TABLE_NAME,
        ["VendorDeviceID"],
        unique=False,
    )
    op.drop_column(TABLE_NAME, "NewVendorDeviceID")
    op.drop_column(TABLE_NAME, "OldVendorDeviceID")
    op.drop_column(TABLE_NAME, "OldGroupID")
    op.drop_column(TABLE_NAME, "NewGroupID")
    DEVICE_STATE_CHANGE.create_trigger(op)
    # ### end Alembic commands ###
