"""add-device-type

Revision ID: e93f00a830b9
Revises: 7c073467cb11
Create Date: 2025-02-13 15:00:39.231706

"""

import sqlalchemy as sa
from alembic import op

from schemas.helpers import insert_device_types
from seeds.device_type import DeviceType

# revision identifiers, used by Alembic.
revision = "e93f00a830b9"
down_revision = "7c073467cb11"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint("uq_DeviceTypeName", "DeviceType", ["Name"])
    session = sa.orm.Session(bind=op.get_bind())
    session.add(DeviceType(Name="Battery Charger"))
    session.commit()
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("uq_DeviceTypeName", "DeviceType", type_="unique")
    session = sa.orm.Session(bind=op.get_bind())
    session.query(DeviceType).filter(DeviceType.Name == "Battery Charger").delete()
    session.commit()
    # ### end Alembic commands ###
