"""unique-constraints

Revision ID: 28e247d29b51
Revises: e93f00a830b9
Create Date: 2025-02-25 16:28:55.402211

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "28e247d29b51"
down_revision = "e93f00a830b9"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(
        "uq_FrostDeviceRevisions_Name", "FrostDeviceRevisions", ["Name"]
    )
    op.create_unique_constraint(
        "uq_BluetoothHardware_VendorID", "BluetoothHardware", ["VendorID"]
    )
    op.create_unique_constraint(
        "uq_SensorHardware_VendorID", "SensorHardware", ["VendorID"]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "uq_FrostDeviceRevisions_Name", "FrostDeviceRevisions", type_="unique"
    )
    op.drop_constraint(
        "uq_BluetoothHardware_VendorID", "BluetoothHardware", type_="unique"
    )
    op.drop_constraint("uq_SensorHardware_VendorID", "SensorHardware", type_="unique")
    # ### end Alembic commands ###
