"""sds_calibration_request_table

Revision ID: a4041861a021
Revises: 5e9de4f702c9
Create Date: 2025-08-06 12:08:29.304217

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "a4041861a021"
down_revision = "5e9de4f702c9"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "SnowDepthCalibrationRequests",
        sa.Column(
            "ID",
            sa.BigInteger(),
            sa.Identity(always=False, start=1, increment=1),
            nullable=False,
        ),
        sa.Column("RWISDeviceID", sa.BigInteger(), nullable=False),
        sa.Column("SnowDepthDeviceID", sa.BigInteger(), nullable=False),
        sa.Column("RequestDateTimeUTC", sa.DateTime(), nullable=False),
        sa.Column("CalibrationDateTimeUTC", sa.DateTime(), nullable=True),
        sa.Column(
            "CalibrationFailed",
            sa.Boolean(),
            server_default=sa.text("((0))"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["RWISDeviceID"],
            ["Devices.ID"],
            name=op.f("fk_SnowDepthCalibrationRequests_RWISDeviceID_Devices"),
        ),
        sa.ForeignKeyConstraint(
            ["SnowDepthDeviceID"],
            ["Devices.ID"],
            name=op.f("fk_SnowDepthCalibrationRequests_SnowDepthDeviceID_Devices"),
        ),
        sa.PrimaryKeyConstraint("ID", name=op.f("pk_SnowDepthCalibrationRequests")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("SnowDepthCalibrationRequests")
    # ### end Alembic commands ###
