"""add_iced_lens

Revision ID: 8af1cdb6b910
Revises: 237fbcf51f9b
Create Date: 2024-09-19 16:07:43.447681

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "8af1cdb6b910"
down_revision = "237fbcf51f9b"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "ComputerVision",
        sa.Column(
            "IcedLens", sa.REAL(), server_default=sa.text("((0))"), nullable=True
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("ComputerVision", "IcedLens")
    # ### end Alembic commands ###
