"""add_columns_to_cv

Revision ID: a02e50288ee0
Revises: 26c102a4eeb8
Create Date: 2024-09-19 14:31:50.637559

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "a02e50288ee0"
down_revision = "26c102a4eeb8"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "ComputerVision",
        sa.Column("Night", sa.REAL(), server_default=sa.text("((0))"), nullable=True),
    )
    op.add_column(
        "ComputerVision",
        sa.Column("Sunny", sa.REAL(), server_default=sa.text("((0))"), nullable=True),
    )
    op.add_column(
        "ComputerVision",
        sa.Column("Cloudy", sa.REAL(), server_default=sa.text("((0))"), nullable=True),
    )
    op.add_column(
        "ComputerVision",
        sa.Column(
            "ClearPavement", sa.REAL(), server_default=sa.text("((0))"), nullable=True
        ),
    )
    op.add_column(
        "ComputerVision",
        sa.Column(
            "WetPavement", sa.REAL(), server_default=sa.text("((0))"), nullable=True
        ),
    )
    op.add_column(
        "ComputerVision",
        sa.Column(
            "SnowOnRoad", sa.REAL(), server_default=sa.text("((0))"), nullable=True
        ),
    )
    op.add_column(
        "ComputerVision",
        sa.Column(
            "PartialSnowOnRoad",
            sa.REAL(),
            server_default=sa.text("((0))"),
            nullable=True,
        ),
    )
    op.add_column(
        "ComputerVision",
        sa.Column("Snowing", sa.REAL(), server_default=sa.text("((0))"), nullable=True),
    )
    op.add_column(
        "ComputerVision",
        sa.Column("Raining", sa.REAL(), server_default=sa.text("((0))"), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("ComputerVision", "Raining")
    op.drop_column("ComputerVision", "Snowing")
    op.drop_column("ComputerVision", "PartialSnowOnRoad")
    op.drop_column("ComputerVision", "SnowOnRoad")
    op.drop_column("ComputerVision", "WetPavement")
    op.drop_column("ComputerVision", "ClearPavement")
    op.drop_column("ComputerVision", "Cloudy")
    op.drop_column("ComputerVision", "Sunny")
    op.drop_column("ComputerVision", "Night")
    # ### end Alembic commands ###
