MAP = {
    "REQUEST_DEFROST_STARTED": "DEVICE_REQUEST_DEFROST",
    "REQUEST_PHOTO_STARTED": "DEVICE_REQUEST_PHOTO",
    "REQUEST_STORM_STARTED": "DEVICE_REQUEST_STORM",
    "REQUEST_WORK_STARTED": "EVENT_REQUEST_WORK",
    "REQUEST_BURST_STARTED": "DEVICE_REQUEST_BURST_PHOTO",
}

NEW_NOTIFICATION_TYPES = (
    ("REQUEST_BURST_STARTED", "Device Request burst photo upload started", 12),
    ("REQUEST_BURST_COMPLETED", "Device Request burst photo upload completed", 13),
)
