"""cv_ncar_columns_nullable

Revision ID: 68f5301ed43e
Revises: a02e50288ee0
Create Date: 2024-09-19 14:52:15.218264

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mssql

# revision identifiers, used by Alembic.
revision = "68f5301ed43e"
down_revision = "a02e50288ee0"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "ComputerVision",
        "NightClearPavement",
        existing_type=mssql.REAL(),
        nullable=True,
        existing_server_default=sa.text("((0))"),
    )
    op.alter_column(
        "ComputerVision",
        "NightSnowing",
        existing_type=mssql.REAL(),
        nullable=True,
        existing_server_default=sa.text("((0))"),
    )
    op.alter_column(
        "ComputerVision",
        "NightWetPavement",
        existing_type=mssql.REAL(),
        nullable=True,
        existing_server_default=sa.text("((0))"),
    )
    op.alter_column(
        "ComputerVision",
        "NightSnowOnRoad",
        existing_type=mssql.REAL(),
        nullable=True,
        existing_server_default=sa.text("((0))"),
    )
    op.alter_column(
        "ComputerVision",
        "NightPartialSnowOnRoad",
        existing_type=mssql.REAL(),
        nullable=True,
        existing_server_default=sa.text("((0))"),
    )
    op.alter_column(
        "ComputerVision",
        "DaySnowing",
        existing_type=mssql.REAL(),
        nullable=True,
        existing_server_default=sa.text("((0))"),
    )
    op.alter_column(
        "ComputerVision",
        "DayPartialSnowOnRoad",
        existing_type=mssql.REAL(),
        nullable=True,
        existing_server_default=sa.text("((0))"),
    )
    op.alter_column(
        "ComputerVision",
        "DayClearPavement",
        existing_type=mssql.REAL(),
        nullable=True,
        existing_server_default=sa.text("((0))"),
    )
    op.alter_column(
        "ComputerVision",
        "DayWetPavement",
        existing_type=mssql.REAL(),
        nullable=True,
        existing_server_default=sa.text("((0))"),
    )
    op.alter_column(
        "ComputerVision",
        "DaySnowOnRoad",
        existing_type=mssql.REAL(),
        nullable=True,
        existing_server_default=sa.text("((0))"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "ComputerVision",
        "DaySnowOnRoad",
        existing_type=mssql.REAL(),
        nullable=False,
        existing_server_default=sa.text("((0))"),
    )
    op.alter_column(
        "ComputerVision",
        "DayWetPavement",
        existing_type=mssql.REAL(),
        nullable=False,
        existing_server_default=sa.text("((0))"),
    )
    op.alter_column(
        "ComputerVision",
        "DayClearPavement",
        existing_type=mssql.REAL(),
        nullable=False,
        existing_server_default=sa.text("((0))"),
    )
    op.alter_column(
        "ComputerVision",
        "DayPartialSnowOnRoad",
        existing_type=mssql.REAL(),
        nullable=False,
        existing_server_default=sa.text("((0))"),
    )
    op.alter_column(
        "ComputerVision",
        "DaySnowing",
        existing_type=mssql.REAL(),
        nullable=False,
        existing_server_default=sa.text("((0))"),
    )
    op.alter_column(
        "ComputerVision",
        "NightPartialSnowOnRoad",
        existing_type=mssql.REAL(),
        nullable=False,
        existing_server_default=sa.text("((0))"),
    )
    op.alter_column(
        "ComputerVision",
        "NightSnowOnRoad",
        existing_type=mssql.REAL(),
        nullable=False,
        existing_server_default=sa.text("((0))"),
    )
    op.alter_column(
        "ComputerVision",
        "NightWetPavement",
        existing_type=mssql.REAL(),
        nullable=False,
        existing_server_default=sa.text("((0))"),
    )
    op.alter_column(
        "ComputerVision",
        "NightSnowing",
        existing_type=mssql.REAL(),
        nullable=False,
        existing_server_default=sa.text("((0))"),
    )
    op.alter_column(
        "ComputerVision",
        "NightClearPavement",
        existing_type=mssql.REAL(),
        nullable=False,
        existing_server_default=sa.text("((0))"),
    )
    # ### end Alembic commands ###
