"""add_vision_alert_conditions

Revision ID: 3a6e654c21a9
Revises: 8af1cdb6b910
Create Date: 2024-10-30 16:32:31.299436

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "3a6e654c21a9"
down_revision = "8af1cdb6b910"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "Alerts",
        sa.Column(
            "VisionConditions",
            sa.String(length=100, collation="SQL_Latin1_General_CP1_CI_AS"),
            nullable=True,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("Alerts", "VisionConditions")
    # ### end Alembic commands ###
