"""add_model_name_column

Revision ID: 237fbcf51f9b
Revises: 68f5301ed43e
Create Date: 2024-09-19 15:35:11.987481

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "237fbcf51f9b"
down_revision = "68f5301ed43e"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "ComputerVision",
        sa.Column(
            "ModelVersion",
            sa.String(length=50, collation="SQL_Latin1_General_CP1_CI_AS"),
            server_default=sa.text("('NCAR Vision')"),
            nullable=True,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("ComputerVision", "ModelVersion")
    # ### end Alembic commands ###
