"""remove-forecasts

Revision ID: 0b8351f26d9a
Revises: 13448daa34e0
Create Date: 2025-03-07 13:21:05.136416

"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mssql

from schemas.views import LatestNCARForecastsSummaryView

# revision identifiers, used by Alembic.
revision = "0b8351f26d9a"
down_revision = "13448daa34e0"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    LatestNCARForecastsSummaryView.drop(op)
    op.drop_index(
        "IDX_ForecastSummary_GeneratedDateTimeUTC", table_name="ForecastSummary"
    )
    op.drop_table("ForecastSummary")
    op.drop_index("IDX_ForecastDataRaw_ForecastSummaryID", table_name="ForecastDataRaw")
    op.drop_table("ForecastDataRaw")
    op.drop_column("DeviceSummary", "ForecastSummaryID")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "DeviceSummary",
        sa.Column("ForecastSummaryID", sa.BIGINT(), autoincrement=False, nullable=True),
    )
    op.create_table(
        "ForecastDataRaw",
        sa.Column(
            "ID",
            sa.BIGINT(),
            sa.Identity(always=False, start=1, increment=1),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column(
            "ForecastSummaryID", sa.BIGINT(), autoincrement=False, nullable=False
        ),
        sa.Column("DeviceID", sa.BIGINT(), autoincrement=False, nullable=False),
        sa.Column(
            "FileName",
            sa.VARCHAR(length=200, collation="SQL_Latin1_General_CP1_CI_AS"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("time_str", sa.DATETIME(), autoincrement=False, nullable=False),
        sa.Column("cloud_cover", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column(
            "d_prate",
            sa.DECIMAL(precision=12, scale=4),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "d_rad",
            sa.DECIMAL(precision=12, scale=4),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "d_sfc_t",
            sa.DECIMAL(precision=12, scale=4),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "d_snod",
            sa.DECIMAL(precision=12, scale=4),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "lrad",
            sa.DECIMAL(precision=12, scale=4),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "prate",
            sa.DECIMAL(precision=12, scale=4),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "pres",
            sa.DECIMAL(precision=12, scale=4),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "ptype",
            sa.DECIMAL(precision=12, scale=4),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "rad", sa.DECIMAL(precision=12, scale=4), autoincrement=False, nullable=True
        ),
        sa.Column(
            "rh", sa.DECIMAL(precision=12, scale=4), autoincrement=False, nullable=True
        ),
        sa.Column(
            "sfc_t",
            sa.DECIMAL(precision=12, scale=4),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "snod",
            sa.DECIMAL(precision=12, scale=4),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "t", sa.DECIMAL(precision=8, scale=4), autoincrement=False, nullable=True
        ),
        sa.Column(
            "vbdsf",
            sa.DECIMAL(precision=8, scale=4),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "wdir", sa.DECIMAL(precision=8, scale=4), autoincrement=False, nullable=True
        ),
        sa.Column(
            "wspd", sa.DECIMAL(precision=8, scale=4), autoincrement=False, nullable=True
        ),
        sa.Column(
            "dewpt",
            sa.DECIMAL(precision=8, scale=4),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "tuned_t",
            sa.DECIMAL(precision=8, scale=4),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "tuned_rh",
            sa.DECIMAL(precision=8, scale=4),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "tuned_dewpt",
            sa.DECIMAL(precision=8, scale=4),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "tuned_rt",
            sa.DECIMAL(precision=8, scale=4),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column("valid_times", sa.BIGINT(), autoincrement=False, nullable=True),
        sa.Column(
            "obs_blend_t",
            sa.DECIMAL(precision=8, scale=4),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "obs_blend_rh",
            sa.DECIMAL(precision=8, scale=4),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "obs_blend_dewpt",
            sa.DECIMAL(precision=8, scale=4),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "obs_blend_rt",
            sa.DECIMAL(precision=8, scale=4),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "window_blend_t",
            sa.DECIMAL(precision=8, scale=4),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "window_blend_rh",
            sa.DECIMAL(precision=8, scale=4),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "window_blend_dewpt",
            sa.DECIMAL(precision=8, scale=4),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "window_blend_rt",
            sa.DECIMAL(precision=8, scale=4),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "CreatedDateTimeUTC", sa.DATETIME(), autoincrement=False, nullable=True
        ),
        sa.Column("global_rc", sa.SMALLINT(), autoincrement=False, nullable=True),
        sa.Column(
            "global_grip",
            sa.DECIMAL(precision=8, scale=4),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column("obs_blend_rc", sa.SMALLINT(), autoincrement=False, nullable=True),
        sa.Column(
            "obs_blend_grip",
            sa.DECIMAL(precision=8, scale=4),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column("window_blend_rc", sa.SMALLINT(), autoincrement=False, nullable=True),
        sa.Column(
            "window_blend_grip",
            sa.DECIMAL(precision=8, scale=4),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column("storm_mode", mssql.BIT(), autoincrement=False, nullable=True),
        sa.PrimaryKeyConstraint(
            "DeviceID", "FileName", "time_str", name="PK_ForecastDataRaw"
        ),
    )
    op.create_index(
        "IDX_ForecastDataRaw_ForecastSummaryID",
        "ForecastDataRaw",
        ["ForecastSummaryID"],
        unique=False,
    )
    op.create_table(
        "ForecastSummary",
        sa.Column(
            "ID",
            sa.BIGINT(),
            sa.Identity(always=False, start=1, increment=1),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column("DeviceID", sa.BIGINT(), autoincrement=False, nullable=False),
        sa.Column(
            "FileName",
            sa.VARCHAR(length=200, collation="SQL_Latin1_General_CP1_CI_AS"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "CreateDateTimeUTC",
            sa.DATETIME(),
            server_default=sa.text("(getdate())"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "GeneratedDateTimeUTC",
            sa.BIGINT(),
            server_default=sa.text("((0))"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "FileDateTimeUTC",
            sa.DATETIME(),
            server_default=sa.text("(getdate())"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "IsComplete",
            mssql.BIT(),
            server_default=sa.text("((1))"),
            autoincrement=False,
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("DeviceID", "FileName", name="PK_Table_1"),
    )
    op.create_index(
        "IDX_ForecastSummary_GeneratedDateTimeUTC",
        "ForecastSummary",
        ["GeneratedDateTimeUTC"],
        unique=False,
    )
    LatestNCARForecastsSummaryView.create(op)
    # ### end Alembic commands ###
