CREATE TABLE devices (
	ID UInt32,
	GroupID UInt64,
	DeviceKey UUID,
	IsActive Boolean,
	VendorDeviceID String,
	VendorTypeCode LowCardinality(String),
	Name String,
	Description String,
	Notes String,
	Zone LowCardinality(String),
	location Point,
	ModifiedDateTimeUTC DateTime64,
	CreatedDateTimeUTC DateTime64,
	Altitude Int16,
	Height Int16,
	SensorHeight Int16,
	Distance Int16,
	CreatedUserID UUID,
	ModifiedUserID UUID,
	VendorProductID LowCardinality(String),
	LastPhotoRequestUTC DateTime64,
	TransmissionInterval Int8,
	LocationType LowCardinality(String),
	SurfaceType LowCardinality(String),
	DeviceState LowCardinality(String),
	DeviceType LowCardinality(String),
	Revision LowCardinality(String),
) ENGINE = ReplacingMergeTree (ModifiedDateTimeUTC)
ORDER BY (ID);
