CREATE OR REPLACE TABLE paired_latest_image_transmissions (
	-- Shared
	DeviceID UInt32 CODEC(T64),
	LocationID UInt32 CODEC(T64),
	VendorDeviceID LowCardinality(String),
	AmbientLight Int32,
	-- transmissions
	ID UInt64 CODEC(Delta, ZSTD),
	CaptureTimestampUTC DATETIME CODEC(Delta, ZSTD),
	TransmissionDateTimeUTC DateTime64 CODEC(Delta, ZSTD),
	SurfaceTemp DECIMAL(6, 2),
	AirTemp DECIMAL(5, 2),
	DewPoint DECIMAL(5, 2),
	Humidity DECIMAL(4, 2),
	HeaterTemp DECIMAL(6, 2),
	-- images
	VendorImageID String,
	CameraVersion LowCardinality(String),
	ImageBucket LowCardinality(String),
	ImageFormat LowCardinality(String),
	ModifiedDateTimeUTC DateTime64 CODEC(Delta, ZSTD),
	ImageCaptureDateTimeUTC DateTime64 CODEC(Delta, ZSTD),
    ImageAssembledDateTimeUTC DateTime64 CODEC(Delta, ZSTD),
    CVAssessmentDateTimeUTC DateTime64 CODEC(Delta, ZSTD),
	IsComplete Boolean,
	Contrast UInt8,
	Brightness UInt8,
	Exposure UInt8,
	Resolution UInt8,
	ImageUrl String,
	ImageID UInt32 CODEC(Delta, ZSTD),
	NightClearPavement DECIMAL(4, 2),
	NightSnowing DECIMAL(4, 2),
	NightWetPavement DECIMAL(4, 2),
	NightSnowOnRoad DECIMAL(4, 2),
	NightPartialSnowOnRoad DECIMAL(4, 2),
	DaySnowing DECIMAL(4, 2),
	DayPartialSnowOnRoad DECIMAL(4, 2),
	DayClearPavement DECIMAL(4, 2),
	DayWetPavement DECIMAL(4, 2),
	DaySnowOnRoad DECIMAL(4, 2),
	Night DECIMAL(4, 2),
	Sunny DECIMAL(4, 2),
	Cloudy DECIMAL(4, 2),
	ClearPavement DECIMAL(4, 2),
	WetPavement DECIMAL(4, 2),
	SnowOnRoad DECIMAL(4, 2),
	PartialSnowOnRoad DECIMAL(4, 2),
	Snowing DECIMAL(4, 2),
	Raining DECIMAL(4, 2),
	ModelVersion LowCardinality(String),
	IcedLens DECIMAL(4, 2),
	Version Int8,
    IsBurstImage Boolean,
	TransmissionType Int8 DEFAULT 2
) ENGINE = ReplacingMergeTree(ImageCaptureDateTimeUTC)
ORDER BY (
		DeviceID,
	)