CREATE MATERIALIZED VIEW pair_transmissions_to_latest_images TO paired_latest_image_transmissions AS
SELECT 
    -- Shared
    i.DeviceID as DeviceID,
	i.DeviceID as LocationID,
	i.VendorDeviceID as VendorDeviceID,
	i.AmbientLight as AmbientLight,
	-- transmissions
	t.ID,
	t.CaptureTimestampUTC as CaptureTimestampUTC,
	t.CaptureDateTimeUTC as TransmissionDateTimeUTC,
	t.SurfaceTemp,
	t.AirTemp,
	t.DewPoint,
	t.Humidity,
	t.HeaterTemp,
	-- images
	i.VendorImageID,
	i.CameraVersion,
	i.ImageBucket,
	i.ImageFormat,
	i.ModifiedDateTimeUTC,
	i.CaptureDateTimeUTC as ImageCaptureDateTimeUTC,
    i.ImageAssembledDateTimeUTC,
    i.CVAssessmentDateTimeUTC,
	i.IsComplete,
	i.Contrast,
	i.Brightness,
	i.Exposure,
	i.Resolution,
	i.ImageUrl,
	i.ImageID,
	i.NightClearPavement,
	i.NightSnowing,
	i.NightWetPavement,
	i.NightSnowOnRoad,
	i.NightPartialSnowOnRoad,
	i.DaySnowing,
	i.DayPartialSnowOnRoad,
	i.DayClearPavement,
	i.DayWetPavement,
	i.DaySnowOnRoad,
	i.Night,
	i.Sunny,
	i.Cloudy,
	i.ClearPavement,
	i.WetPavement,
	i.SnowOnRoad,
	i.PartialSnowOnRoad,
	i.Snowing,
	i.Raining,
	i.ModelVersion,
	i.IcedLens,
	i.Version,
    i.IsBurstImage,
    2 as TransmissionType
FROM latest_images i 
JOIN (
	SELECT * FROM transmissions t where (t.DeviceID, t.CaptureDateTimeUTC) in (SELECT (i.DeviceID, i.TransmissionCaptureDateTimeUTC) FROM latest_images i)
) as t ON t.DeviceID = i.DeviceID AND t.CaptureDateTimeUTC = i.TransmissionCaptureDateTimeUTC