"""group_subscriptions

Revision ID: 9c95654a68db
Revises: 0b8351f26d9a
Create Date: 2025-04-01 15:33:48.808884

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "9c95654a68db"
down_revision = "0b8351f26d9a"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "GroupSubscriptions",
        sa.Column("GroupID", sa.BigInteger(), nullable=False),
        sa.Column(
            "Name",
            sa.String(length=100, collation="SQL_Latin1_General_CP1_CI_AS"),
            nullable=False,
        ),
        sa.Column(
            "CreatedDateTimeUTC",
            sa.DateTime(),
            server_default=sa.text("(getdate())"),
            nullable=False,
        ),
        sa.Column(
            "ModifiedDateTimeUTC",
            sa.DateTime(),
            server_default=sa.text("(getdate())"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["GroupID"],
            ["Groups.GroupID"],
            name=op.f("fk_GroupSubscriptions_GroupID_Groups"),
        ),
        sa.PrimaryKeyConstraint("GroupID", "Name", name=op.f("pk_GroupSubscriptions")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("GroupSubscriptions")
    # ### end Alembic commands ###
