"""expecting_replacements

Revision ID: 11f626774316
Revises: 1aca50f1f41f
Create Date: 2023-09-05 11:46:52.755925

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy import text
from sqlalchemy.dialects import mssql
from schemas.other_objects.triggers import ENFORCE_TIMEOUT_ON_EXPECTING_REPLACEMENTS


# revision identifiers, used by Alembic.
revision = "11f626774316"
down_revision = "1aca50f1f41f"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "Groups",
        sa.Column(
            "ExpectReplacementDevices",
            sa.Boolean(),
            server_default=text("(0)"),
            nullable=False,
        ),
    )
    op.add_column(
        "Groups",
        sa.Column(
            "ExpectReplacementDevicesTimeout",
            mssql.DATETIME2(),
            server_default=sa.text("(DATEADD(MONTH, 1, GETDATE()))"),
            nullable=True,
        ),
    )
    ENFORCE_TIMEOUT_ON_EXPECTING_REPLACEMENTS.create_trigger(op)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    ENFORCE_TIMEOUT_ON_EXPECTING_REPLACEMENTS.drop_trigger(op)
    op.drop_column("Groups", "ExpectReplacementDevicesTimeout")
    op.drop_column("Groups", "ExpectReplacementDevices")
    # ### end Alembic commands ###
