"""user_configuration_table

Revision ID: 53e8757b3f86
Revises: 094379e75d4c
Create Date: 2024-02-27 11:31:32.343276

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mssql

# revision identifiers, used by Alembic.
revision = "53e8757b3f86"
down_revision = "094379e75d4c"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "UserConfigurations",
        sa.Column("UserID", mssql.UNIQUEIDENTIFIER(), nullable=False),
        sa.Column("DefaultViewGroupID", sa.BigInteger(), nullable=True),
        sa.Column("EmployedAtGroupID", sa.BigInteger(), nullable=True),
        sa.ForeignKeyConstraint(
            ["DefaultViewGroupID"],
            ["Groups.GroupID"],
            name=op.f("fk_UserConfigurations_DefaultViewGroupID_Groups"),
        ),
        sa.ForeignKeyConstraint(
            ["EmployedAtGroupID"],
            ["Groups.GroupID"],
            name=op.f("fk_UserConfigurations_EmployedAtGroupID_Groups"),
        ),
        sa.ForeignKeyConstraint(
            ["UserID"], ["Users.ID"], name=op.f("fk_UserConfigurations_UserID_Users")
        ),
        sa.PrimaryKeyConstraint("UserID", name=op.f("pk_UserConfigurations")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("UserConfigurations")
    # ### end Alembic commands ###
