"""
Adds the DeviceState Column to the Devices table
Also:
- Initial values on the DeviceState Column
- Enforces DeviceState contraints
- Adds triggers to write state changes to the DataLineage Table

Revision ID: a1fd842b0ccb
Revises: 086ffb27dd84
Create Date: 2023-09-05 11:46:10.238919

"""
from alembic import op
import sqlalchemy as sa

from schemas.other_objects.triggers import DEVICE_INITIAL_STATE, DEVICE_STATE_CHANGE


# revision identifiers, used by Alembic.
revision = "a1fd842b0ccb"
down_revision = "086ffb27dd84"
branch_labels = None
depends_on = None


def upgrade() -> None:
    from migrations.helpers import (
        insert_device_state_constraints,
        set_default_device_state,
    )

    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("Devices", sa.Column("DeviceState", sa.SmallInteger(), nullable=True))
    DEVICE_STATE_CHANGE.create_trigger(op)
    DEVICE_INITIAL_STATE.create_trigger(op)
    #### ADD NON-NULLABLE VALUES
    set_default_device_state(op, sa.orm)

    op.alter_column(
        "Devices",
        "DeviceState",
        existing_type=sa.SmallInteger(),
        nullable=False,
    )

    op.create_index(
        op.f("Devices_DeviceState_IX"), "Devices", ["DeviceState"], unique=False
    )
    op.create_foreign_key(
        op.f("fk_Devices_DeviceState_DeviceStateType"),
        "Devices",
        "DeviceStateType",
        ["DeviceState"],
        ["ID"],
    )
    # ### end Alembic commands ###

    insert_device_state_constraints(op)


def downgrade() -> None:
    from migrations.helpers import (
        drop_device_state_constraints,
    )

    DEVICE_STATE_CHANGE.drop_trigger(op)
    DEVICE_INITIAL_STATE.drop_trigger(op)
    op.drop_constraint(
        op.f("fk_Devices_DeviceState_DeviceStateType"), "Devices", type_="foreignkey"
    )
    op.drop_index(op.f("Devices_DeviceState_IX"), table_name="Devices")
    drop_device_state_constraints(op)
    op.drop_column("Devices", "DeviceState")
    # ### end Alembic commands ###
