"""computer_vision

Revision ID: c9f35647fdc5
Revises: e7f55c329c1c
Create Date: 2024-03-13 13:48:03.770211

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "c9f35647fdc5"
down_revision = "e7f55c329c1c"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "ComputerVision",
        sa.Column(
            "ID",
            sa.BigInteger(),
            sa.Identity(always=False, start=1, increment=1),
            nullable=False,
        ),
        sa.Column("ImageID", sa.BigInteger(), nullable=False),
        sa.Column(
            "NightClearPavement",
            sa.REAL(),
            server_default=sa.text("((0))"),
            nullable=False,
        ),
        sa.Column(
            "NightSnowing", sa.REAL(), server_default=sa.text("((0))"), nullable=False
        ),
        sa.Column(
            "NightWetPavement",
            sa.REAL(),
            server_default=sa.text("((0))"),
            nullable=False,
        ),
        sa.Column(
            "NightSnowOnRoad",
            sa.REAL(),
            server_default=sa.text("((0))"),
            nullable=False,
        ),
        sa.Column(
            "NightPartialSnowOnRoad",
            sa.REAL(),
            server_default=sa.text("((0))"),
            nullable=False,
        ),
        sa.Column(
            "DaySnowing", sa.REAL(), server_default=sa.text("((0))"), nullable=False
        ),
        sa.Column(
            "DayPartialSnowOnRoad",
            sa.REAL(),
            server_default=sa.text("((0))"),
            nullable=False,
        ),
        sa.Column(
            "DayClearPavement",
            sa.REAL(),
            server_default=sa.text("((0))"),
            nullable=False,
        ),
        sa.Column(
            "DayWetPavement", sa.REAL(), server_default=sa.text("((0))"), nullable=False
        ),
        sa.Column(
            "DaySnowOnRoad", sa.REAL(), server_default=sa.text("((0))"), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["ImageID"],
            ["DeviceImages.ID"],
            name=op.f("fk_ComputerVision_ImageID_DeviceImages"),
        ),
        sa.PrimaryKeyConstraint("ImageID", name=op.f("pk_ComputerVision")),
    )
    op.create_index(
        op.f("ComputerVision_ImageID_IX"), "ComputerVision", ["ImageID"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ComputerVision_ImageID_IX"), table_name="ComputerVision")
    op.drop_table("ComputerVision")
    # ### end Alembic commands ###
