"""index_image_urls

Revision ID: ddc14f11cac7
Revises: c9f35647fdc5
Create Date: 2024-03-13 13:56:17.297934

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "ddc14f11cac7"
down_revision = "c9f35647fdc5"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index("IDX_ImageUrl", "DeviceImages", ["ImageUrl"], unique=False)
    op.create_index(
        "IDX_ImageUrlProcessed", "DeviceImages", ["ImageUrlProcessed"], unique=False
    )
    op.create_index(
        "IDX_ImageUrlUpscale", "DeviceImages", ["ImageUrlUpscale"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("IDX_ImageUrlUpscale", table_name="DeviceImages")
    op.drop_index("IDX_ImageUrlProcessed", table_name="DeviceImages")
    op.drop_index("IDX_ImageUrl", table_name="DeviceImages")
    # ### end Alembic commands ###
