"""forecasts_interval_config

Revision ID: e7f55c329c1c
Revises: 53e8757b3f86
Create Date: 2024-02-27 16:37:12.219130

"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mssql

# revision identifiers, used by Alembic.
revision = "e7f55c329c1c"
down_revision = "53e8757b3f86"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "UserConfigurations",
        sa.Column(
            "ForecastIntervalHours",
            mssql.TINYINT(),
            nullable=False,
            server_default="72",
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("UserConfigurations", "ForecastIntervalHours")
    # ### end Alembic commands ###
