"""increase-zone-char-limit

Revision ID: 530a79ad905b
Revises: 32265edd8275
Create Date: 2025-01-06 13:55:06.928995

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "530a79ad905b"
down_revision = "32265edd8275"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "Devices",
        "Zone",
        existing_type=sa.VARCHAR(length=50, collation="SQL_Latin1_General_CP1_CI_AS"),
        type_=sa.String(length=150),
        existing_nullable=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "Devices",
        "Zone",
        existing_type=sa.VARCHAR(length=150, collation="SQL_Latin1_General_CP1_CI_AS"),
        type_=sa.String(length=50),
        existing_nullable=True,
    )
    # ### end Alembic commands ###
