"""cleanup_devices_and_images

Revision ID: ca6f216a0e74
Revises: cbfaa34afe0c
Create Date: 2025-02-13 07:58:21.994924

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "ca6f216a0e74"
down_revision = "cbfaa34afe0c"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("Devices_Name_IX"), table_name="Devices")
    op.alter_column(
        "Devices",
        "Name",
        existing_type=sa.VARCHAR(length=50, collation="SQL_Latin1_General_CP1_CI_AS"),
        nullable=False,
    )
    op.create_index(op.f("Devices_Name_IX"), "Devices", ["Name"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("Devices_Name_IX", table_name="Devices")
    op.alter_column(
        "Devices",
        "Name",
        existing_type=sa.VARCHAR(length=50, collation="SQL_Latin1_General_CP1_CI_AS"),
        nullable=True,
    )
    op.create_index(op.f("Devices_Name_IX"), "Devices", ["Name"], unique=False)
    # ### end Alembic commands ###
