"""normalize_revisions

Revision ID: 5a4388cf309d
Revises: 675203a95d1b
Create Date: 2024-08-30 12:52:28.858768

"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.sql import text
from sqlalchemy.dialects import mssql


from schemas.schema import BluetoothHardware

# revision identifiers, used by Alembic.
revision = "5a4388cf309d"
down_revision = "675203a95d1b"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    session = sa.orm.Session(op.get_bind())
    op.create_table(
        "FirmwareVersions",
        sa.Column(
            "ID",
            sa.SmallInteger(),
            sa.Identity(always=False, start=1, increment=1),
            nullable=False,
        ),
        sa.Column(
            "Version",
            sa.String(length=50, collation="SQL_Latin1_General_CP1_CI_AS"),
            nullable=True,
        ),
        sa.Column(
            "IsActive", sa.Boolean(), server_default=sa.text("((1))"), nullable=False
        ),
        sa.Column(
            "S3ArtifactURL",
            sa.String(length=2000, collation="SQL_Latin1_General_CP1_CI_AS"),
            nullable=True,
        ),
        sa.Column(
            "BinarySHA1",
            sa.String(length=50, collation="SQL_Latin1_General_CP1_CI_AS"),
            nullable=True,
        ),
        sa.PrimaryKeyConstraint("ID", name=op.f("pk_FirmwareVersions")),
    )
    op.create_table(
        "SDSEncryptionKeys",
        sa.Column(
            "ID",
            sa.BigInteger(),
            sa.Identity(always=False, start=1, increment=1),
            nullable=False,
        ),
        sa.Column(
            "Key",
            sa.String(length=5000, collation="SQL_Latin1_General_CP1_CI_AS"),
            nullable=True,
        ),
        sa.Column(
            "CreatedDateTimeUTC",
            sa.DateTime(),
            server_default=sa.text("(getdate())"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("ID", name=op.f("pk_SDSEncryptionKeys")),
    )
    op.create_table(
        "SensorHardware",
        sa.Column(
            "ID",
            sa.SmallInteger(),
            sa.Identity(always=False, start=1, increment=1),
            nullable=False,
        ),
        sa.Column(
            "VendorID",
            sa.String(length=50, collation="SQL_Latin1_General_CP1_CI_AS"),
            nullable=True,
        ),
        sa.Column(
            "CreatedDateTimeUTC",
            sa.DateTime(),
            server_default=sa.text("(getdate())"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("ID", name=op.f("pk_SensorHardware")),
    )
    op.create_table(
        "FrostDeviceRevisions",
        sa.Column(
            "ID",
            sa.SmallInteger(),
            sa.Identity(always=False, start=1, increment=1),
            nullable=False,
        ),
        sa.Column(
            "Name",
            sa.String(length=50, collation="SQL_Latin1_General_CP1_CI_AS"),
            nullable=True,
        ),
        sa.Column("HardwareRevisionID", sa.SmallInteger(), nullable=True),
        sa.Column("BluetoothRevisionID", sa.BigInteger(), nullable=True),
        sa.Column(
            "ModifiedDateTimeUTC",
            sa.DateTime(),
            server_default=sa.text("(getdate())"),
            nullable=False,
        ),
        sa.Column(
            "IsActive", sa.Boolean(), server_default=sa.text("((1))"), nullable=False
        ),
        sa.Column(
            "Description",
            sa.String(length=2000, collation="SQL_Latin1_General_CP1_CI_AS"),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["BluetoothRevisionID"],
            ["BluetoothHardware.ID"],
            name=op.f("fk_FrostDeviceRevisions_BluetoothRevisionID_BluetoothHardware"),
        ),
        sa.ForeignKeyConstraint(
            ["HardwareRevisionID"],
            ["SensorHardware.ID"],
            name=op.f("fk_FrostDeviceRevisions_HardwareRevisionID_SensorHardware"),
        ),
        sa.PrimaryKeyConstraint("ID", name=op.f("pk_FrostDeviceRevisions")),
    )
    op.add_column(
        "BluetoothHardware",
        sa.Column(
            "VendorID",
            sa.String(length=50, collation="SQL_Latin1_General_CP1_CI_AS"),
            nullable=True,
        ),
    )
    op.add_column(
        "BluetoothHardware",
        sa.Column(
            "CreatedDateTimeUTC",
            sa.DateTime(),
            server_default=sa.text("(getdate())"),
            nullable=False,
        ),
    )
    constraints = session.execute(
        text(
            """
            SELECT obj_Constraint.NAME AS 'constraint_name', obj_table.Name as 'table'
            FROM   sys.objects obj_table 
                JOIN sys.objects obj_Constraint 
                    ON obj_table.object_id = obj_Constraint.parent_object_id 
                JOIN sys.sysconstraints constraints 
                        ON constraints.constid = obj_Constraint.object_id 
                JOIN sys.columns columns 
                        ON columns.object_id = obj_table.object_id 
                    AND columns.column_id = constraints.colid 
            WHERE obj_table.NAME='BluetoothHardware'
            and columns.Name in ('ProductID', 'IsActive')
        """
        )
    ).all()
    for constraint, table_name in constraints:
        op.drop_constraint(constraint, table_name)
    op.drop_column(
        "BluetoothHardware",
        "ProductID",
    )
    op.drop_column("BluetoothHardware", "SecretKey")
    op.drop_column("BluetoothHardware", "Name")
    op.drop_column("BluetoothHardware", "IsActive")
    op.drop_column("BluetoothHardware", "Description")
    # ### end Alembic commands ###


def downgrade() -> None:
    session = sa.orm.Session(op.get_bind())
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "BluetoothHardware",
        sa.Column(
            "Description",
            sa.VARCHAR(length=2000, collation="SQL_Latin1_General_CP1_CI_AS"),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "BluetoothHardware",
        sa.Column(
            "IsActive",
            mssql.BIT(),
            server_default=sa.text("((0))"),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.add_column(
        "BluetoothHardware",
        sa.Column(
            "Name",
            sa.VARCHAR(length=50, collation="SQL_Latin1_General_CP1_CI_AS"),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "BluetoothHardware",
        sa.Column(
            "SecretKey",
            sa.VARCHAR(length=32, collation="SQL_Latin1_General_CP1_CI_AS"),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.add_column(
        "BluetoothHardware",
        sa.Column(
            "ProductID",
            sa.VARCHAR(length=8, collation="SQL_Latin1_General_CP1_CI_AS"),
            server_default=sa.text("('1')"),
            autoincrement=False,
            nullable=False,
        ),
    )
    constraints = session.execute(
        text(
            """
            SELECT obj_Constraint.NAME AS 'constraint_name', obj_table.Name as 'table'
            FROM   sys.objects obj_table 
                JOIN sys.objects obj_Constraint 
                    ON obj_table.object_id = obj_Constraint.parent_object_id 
                JOIN sys.sysconstraints constraints 
                        ON constraints.constid = obj_Constraint.object_id 
                JOIN sys.columns columns 
                        ON columns.object_id = obj_table.object_id 
                    AND columns.column_id = constraints.colid 
            WHERE obj_table.NAME='BluetoothHardware'
            and columns.Name in ('CreatedDateTimeUTC', 'VendorID')
        """
        )
    ).all()
    for constraint, table_name in constraints:
        op.drop_constraint(constraint, table_name)
    op.drop_column("BluetoothHardware", "CreatedDateTimeUTC")
    op.drop_column("BluetoothHardware", "VendorID")
    op.drop_table("FrostDeviceRevisions")
    op.drop_table("SensorHardware")
    op.drop_table("SDSEncryptionKeys")
    op.drop_table("FirmwareVersions")
    # ### end Alembic commands ###
