"""snow_depth_readings

Revision ID: 0510608df920
Revises: a3c7f389aa3e
Create Date: 2024-07-11 14:03:32.945341

"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mssql

# revision identifiers, used by Alembic.
revision = "0510608df920"
down_revision = "a3c7f389aa3e"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "SnowDepthReadings",
        sa.Column(
            "ID",
            sa.BigInteger(),
            sa.Identity(always=False, start=1, increment=1),
            nullable=False,
        ),
        sa.Column("DeviceID", sa.BigInteger(), nullable=False),
        sa.Column("DistanceMm", sa.SmallInteger(), nullable=False),
        sa.Column("BatteryMv", sa.Integer(), nullable=False),
        sa.Column("RssiPower", sa.SmallInteger, nullable=False),
        sa.Column("Version", sa.Integer(), nullable=False),
        sa.Column("TemperatureC", sa.SmallInteger(), nullable=False),
        sa.Column("ReferenceDepthMm", sa.SmallInteger(), nullable=False),
        sa.Column("Reserved1", sa.SmallInteger(), nullable=False),
        sa.Column("Reserved2", sa.SmallInteger(), nullable=False),
        sa.Column("Error", mssql.TINYINT(), nullable=True),
        sa.Column(
            "CreatedDateTimeUTC",
            sa.DateTime(),
            server_default=sa.text("(getdate())"),
            nullable=False,
        ),
        sa.Column("CaptureDateTimeUTC", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["DeviceID"],
            ["Devices.ID"],
            name=op.f("fk_SnowDepthReadings_DeviceID_Devices"),
        ),
        sa.PrimaryKeyConstraint(
            "ID", name=op.f("pk_SnowDepthReadings"), mssql_clustered=False
        ),
    )
    op.create_index(
        "IDX_SnowDepthReadings_DeviceID_CaptureDateTimeUTC",
        "SnowDepthReadings",
        ["DeviceID", sa.text("[CaptureDateTimeUTC] DESC")],
        unique=False,
        mssql_clustered=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "IDX_SnowDepthReadings_DeviceID_CaptureDateTimeUTC",
        table_name="SnowDepthReadings",
        mssql_clustered=True,
    )
    op.drop_table("SnowDepthReadings")
    # ### end Alembic commands ###
