"""normalize_revisions4

Revision ID: 7df85426e98c
Revises: b7df821a5abd
Create Date: 2024-08-30 14:04:23.010493

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "7df85426e98c"
down_revision = "b7df821a5abd"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("Devices", sa.Column("Revision", sa.SmallInteger(), nullable=True))
    op.create_foreign_key(
        op.f("fk_Devices_Revision_FrostDeviceRevisions"),
        "Devices",
        "FrostDeviceRevisions",
        ["Revision"],
        ["ID"],
    )
    op.add_column(
        "SDSEncryptionKeys", sa.Column("DeviceID", sa.BigInteger(), nullable=False)
    )
    op.create_foreign_key(
        op.f("fk_SDSEncryptionKeys_DeviceID_Devices"),
        "SDSEncryptionKeys",
        "Devices",
        ["DeviceID"],
        ["ID"],
    )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("fk_SDSEncryptionKeys_DeviceID_Devices"),
        "SDSEncryptionKeys",
        type_="foreignkey",
    )
    op.drop_column("SDSEncryptionKeys", "DeviceID")
    op.drop_constraint(
        op.f("fk_Devices_Revision_FrostDeviceRevisions"), "Devices", type_="foreignkey"
    )
    op.drop_column("Devices", "Revision")
    # ### end Alembic commands ###
    op.drop_constraint("CK_BluetoothHardware_VendorID_Unique", "BluetoothHardware")
    op.drop_constraint("CK_SensorHardware_VendorID_Unique", "SensorHardware")
