"""cleanup_tables

Revision ID: 649f90414e85
Revises: e5c596433d57
Create Date: 2024-07-02 11:10:30.110048

"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mssql

# revision identifiers, used by Alembic.
revision = "649f90414e85"
# down_revision = "e5c596433d57" # Marking this revision as non-reversible
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("ReportLogs")
    op.drop_table("ReportRecipients")
    op.drop_table("sysdiagrams")
    op.drop_table("ReportLocations")
    op.drop_table("UserLocations")

    # ### end Alembic commands ###


def downgrade() -> None:
    pass
